version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend_network

  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - db
    env_file: .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 backend.wsgi:application"
    expose:
      - "8000"
    ports:
      - "8000:8000"
    networks:
      - backend_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - backend_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  backend_network:
    driver: bridge
