# Generated by Django 5.2 on 2025-04-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='movie_watched',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='main.animemovie'),
        ),
    ]
